name: SnowFall
version: '${project.version}'
main: de.twyco.snowfall.SnowFall
api-version: 1.19
authors: [Twyco]
description: Plugin für stegi Sagt
website: twyco.de
load: POSTWORLD
commands:
  snowfall: